[package]
name = "jadren-lexer"
description = "Lossless lexer for the Jadren programming language"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
jadren-diagnostics = { path = "../jadren-diagnostics" }
jadren-source = { path = "../jadren-source" }

[lints]
workspace = true
