[package]
name = "jadren-syntax"
description = "Lossless syntax tree representation for the Jadren frontend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
jadren-lexer = { path = "../jadren-lexer" }
jadren-source = { path = "../jadren-source" }

[lints]
workspace = true
