[package]
name = "json-object-exact-project"
version = "0.1.0"
edition = "2026"

[dependencies]
jadren-app = { path = "../../stdlib/app" }
jadren-json = { path = "../../stdlib/json" }

[targets]
library = true
